# Introdução ao `numpy`

In [2]:
path = './'

In [3]:
import numpy as np
import matplotlib.pyplot as plt  # Biblioteca para gerar gráficos

Vamos criar umas matrizes e vetores para começar...

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\ &
\boldsymbol{B} &= \begin{bmatrix}1 & 3\\ 5 & 7\end{bmatrix}\\\\
\boldsymbol{v}_1 &= \begin{bmatrix}5 & 3\end{bmatrix}\ &
\boldsymbol{v}_2 &= \begin{bmatrix}9 & 2 & 1\end{bmatrix}
\end{aligned}$$

In [4]:
A = np.array([[2,0],[4,6],[8,2]])
B = np.array([[1,3],[5,7]])
v1 = np.array([5,3])
v2 = np.array([9,2,1])

In [5]:
print("Dimensão de A:", A.shape)
print("Dimensão de B:", B.shape)
print("Dimensão de v1:", v1.shape)
print("Dimensão de v2:", v1.shape)

Dimensão de A: (3, 2)
Dimensão de B: (2, 2)
Dimensão de v1: (2,)
Dimensão de v2: (2,)


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\boldsymbol{A}^{\top} &= \begin{bmatrix}2 & 4 & 8\\ 0 & 6 & 2\end{bmatrix}
\end{aligned}$$

In [6]:
print("Matriz original:")
print(A)
print("Matriz transposta:")
print(A.T)

Matriz original:
[[2 0]
 [4 6]
 [8 2]]
Matriz transposta:
[[2 4 8]
 [0 6 2]]


$$\begin{aligned}
\boldsymbol{A}[0] &= \begin{bmatrix}2 & 0\end{bmatrix}\\
\boldsymbol{A}[[0,2]] &= \begin{bmatrix}2 & 0\\ 8 & 2\end{bmatrix}\\
\end{aligned}$$

In [7]:
print("Primeira linha de A:")
print(A[0], "dimensão:", A[0].shape) # Primeira linha de A
print("Primeira e terceira linha de A:")
print(A[[0,2]], "dimensão:", A[[0,2]].shape) # Primeira e terceira linha de A
print("Primeira linha de A (mantendo 2 dimensões):")
print(A[[0]], "dimensão:", A[[0]].shape) # Primeira linha de A (mantendo 2 dimensões)

Primeira linha de A:
[2 0] dimensão: (2,)
Primeira e terceira linha de A:
[[2 0]
 [8 2]] dimensão: (2, 2)
Primeira linha de A (mantendo 2 dimensões):
[[2 0]] dimensão: (1, 2)


$$\begin{aligned}
\boldsymbol{A}[:,0] &= \begin{bmatrix}2 & 4 & 8\end{bmatrix}\\
\boldsymbol{A}[:,[0]] &= \begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}
\end{aligned}$$

In [8]:
print("Primeira coluna do A:")
print(A[:,0], "dimensão:", A[:,0].shape) # Primeira coluna do A
print("Primeira e segunda coluna do A:")
print(A[:,[0,1]], "dimensão:", A[:,[0,1]].shape) # Primeira e segunda coluna do A
print("Primeira coluna do A (mantendo 2 dimensões):")
print(A[:,[0]], "dimensão:", A[:,[0]].shape) # Primeira coluna do A (mantendo 2 dimensões)

Primeira coluna do A:
[2 4 8] dimensão: (3,)
Primeira e segunda coluna do A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
Primeira coluna do A (mantendo 2 dimensões):
[[2]
 [4]
 [8]] dimensão: (3, 1)


$$\begin{aligned}
\left[\begin{bmatrix}2 & 4 & 8\end{bmatrix}; \begin{bmatrix}1 & 2 & 3\end{bmatrix}\right] &= \begin{bmatrix}2 & 4 & 8\\1 & 2 & 3\end{bmatrix}\\
\left[\begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}, \begin{bmatrix}1 \\ 2 \\ 3\end{bmatrix}\right] &= \begin{bmatrix}2 & 1 \\ 4 & 2 \\ 8 & 3\end{bmatrix}
\end{aligned}$$

In [9]:
a = np.array([2, 4, 8]).reshape((1,-1))
b = np.array([1, 2, 3]).reshape((1,-1))
ab = np.r_[a,b]

print(a, "dimensão:", a.shape)
print(b, "dimensão:", b.shape)
print(ab, "dimensão:", ab.shape) # row stack

[[2 4 8]] dimensão: (1, 3)
[[1 2 3]] dimensão: (1, 3)
[[2 4 8]
 [1 2 3]] dimensão: (2, 3)


In [10]:
c = np.array([2, 4, 8]).reshape((-1,1))
d = np.array([1, 2, 3]).reshape((-1,1))
cd = np.c_[c,d]

print(c, "dimensão:", c.shape)
print(d, "dimensão:", d.shape)
print(cd, "dimensão:", cd.shape) # column stack

[[2]
 [4]
 [8]] dimensão: (3, 1)
[[1]
 [2]
 [3]] dimensão: (3, 1)
[[2 1]
 [4 2]
 [8 3]] dimensão: (3, 2)


## Matrizes notáveis

$$\begin{aligned}
\boldsymbol{I}_n = \mathtt{np.eye(n)} &= \begin{bmatrix}1 & 0 & \ldots\\ 0 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 1\end{bmatrix}&
\boldsymbol{0}_{n,m} = \mathtt{np.zeros((n,m))} &= \begin{bmatrix}0 & 0 & \ldots\\ 0 & 0 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 0\end{bmatrix}\\
\boldsymbol{1}_{n,m} = \mathtt{np.ones((n,m))} &= \begin{bmatrix}1 & 1 & \ldots\\ 1 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 1 & \ldots & 1\end{bmatrix}\\
\end{aligned}$$

In [11]:
print("Matriz identidade de ordem 5:")
print(np.eye(5))
print("Matriz de zeros 5x3:")
print(np.zeros((5,3)))
print("Matriz de uns 3x1:")
print(np.ones((3,1)))

Matriz identidade de ordem 5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Matriz de zeros 5x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de uns 3x1:
[[1.]
 [1.]
 [1.]]


Além dessas matrizes notáveis, também podemos fazer matrizes aleatórias:

`np.random.rand(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.rand(n,m)}]_{ij} \sim \mathcal{U}(0,1)$.

Ou seja, $[\mathtt{np.random.rand(n,m)}]_{ij} \in [0,1)$

`np.random.randn(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.randn(n,m)}]_{ij} \sim \mathcal{N}(0,1)$

Ou seja, $[\mathtt{np.random.randn(n,m)}]_{ij} \in (-\infty,+\infty)$

In [12]:
print("Matriz 5x3 de números aleatórios amostrados de U(0,1):")
print(np.random.rand(5,3))
print("Matriz 2x2 de números aleatórios amostrados de N(0,1):")
print(np.random.randn(2,2))

Matriz 5x3 de números aleatórios amostrados de U(0,1):
[[0.86665044 0.7166549  0.54693323]
 [0.92026379 0.9216229  0.1159483 ]
 [0.61173383 0.07847528 0.26750419]
 [0.44995966 0.2491284  0.06080114]
 [0.2654689  0.93901636 0.19746402]]
Matriz 2x2 de números aleatórios amostrados de N(0,1):
[[ 1.74332685  0.5761559 ]
 [-0.73964255  1.08742307]]


## Operações lineares

Produto de escalares por matrizes:
$$\begin{aligned}
5\boldsymbol{A} &= \begin{bmatrix}2\cdot 5 & 0\cdot 5\\ 4\cdot 5 & 6\cdot 5\\ 8\cdot 5 & 2\cdot 5\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}10 & 0\\ 20 & 30\\ 40 & 10\end{bmatrix}
\end{aligned}$$

In [13]:
print(5 * A)

[[10  0]
 [20 30]
 [40 10]]


Soma de matrizes:
$$\begin{aligned}
\boldsymbol{A}+\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}4 & 0\\ 8 & 12\\ 26 & 4\end{bmatrix}
\end{aligned}$$

In [14]:
print(A + A)

[[ 4  0]
 [ 8 12]
 [16  4]]


Produto com broadcast (difusão) de um vetor por uma matriz:
$$\begin{aligned}
\boldsymbol{v}_1 \bullet \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\bullet\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5\cdot 2 & 3\cdot 0\\ 5\cdot 4 & 3\cdot 6\\ 5\cdot 8 & 3\cdot 2\end{bmatrix}\\
&= \begin{bmatrix}10 & 0\\ 20 & 18\\ 40 & 6\end{bmatrix}\\
\end{aligned}$$

In [15]:
print(v1 * A)

[[10  0]
 [20 18]
 [40  6]]


Soma com broadcast (difusão) de um vetor por uma matriz:
$$\begin{aligned}
\boldsymbol{v}_1 \oplus \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\oplus\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5 & 3\\ 5 & 3\\ 5 & 3\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
&= \begin{bmatrix}7 & 3\\ 9 & 9\\ 13 & 5\end{bmatrix}\\
\end{aligned}$$

In [16]:
print(v1 + A)

[[ 7  3]
 [ 9  9]
 [13  5]]


Cuidado com as dimensões das variáveis:

In [17]:
print("Vetor v2:")
print(v2, "dimensão:", v2.shape)
print("Matriz A:")
print(A, "dimensão:", A.shape)
try:
    v2 + A
except Exception as e:
    print(e)

Vetor v2:
[9 2 1] dimensão: (3,)
Matriz A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
operands could not be broadcast together with shapes (3,) (3,2) 


In [18]:
print("Matriz A:")
print(A, "dimensão:", A.shape)
print("Matriz B:")
print(B, "dimensão:", B.shape)
try:
    A + B
except Exception as e:
    print(e)

Matriz A:
[[2 0]
 [4 6]
 [8 2]] dimensão: (3, 2)
Matriz B:
[[1 3]
 [5 7]] dimensão: (2, 2)
operands could not be broadcast together with shapes (3,2) (2,2) 


## Operações não-lineares

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{A ** 2} &= \begin{bmatrix}2^2 & 0^2\\ 4^2 & 6^2\\ 8^2 & 2^2\end{bmatrix}
\end{aligned}$$

In [19]:
print(A ** 2)

[[ 4  0]
 [16 36]
 [64  4]]


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.sqrt(A)} &= \begin{bmatrix}\sqrt{2} & \sqrt{0}\\ \sqrt{4} & \sqrt{6}\\ \sqrt{8} & \sqrt{2}\end{bmatrix}\\
\mathtt{A ** 0.5} &= \begin{bmatrix}2^\frac{1}{2} & 0^\frac{1}{2}\\ 4^\frac{1}{2} & 6^\frac{1}{2}\\ 8^\frac{1}{2} & 2^\frac{1}{2}\end{bmatrix}
\end{aligned}$$

In [20]:
print(np.sqrt(A))
print(A ** 0.5)

[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]
[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]


## Operações de agregação

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A)} &= \frac{2 + 0 + 4 + 6 + 8 + 2}{2\cdot 3}\\
\mathtt{np.sum(A)} &= 2 + 0 + 4 + 6 + 8 + 2\\
\mathtt{np.prod(A)} &= 2 \cdot 0 \cdot 4 \cdot 6 \cdot 8 \cdot 2\\
\end{aligned}$$

In [21]:
np.mean(A), np.sum(A), np.prod(A)

(np.float64(3.6666666666666665), np.int64(22), np.int64(0))

In [22]:
A.mean(), A.sum(), A.prod()

(np.float64(3.6666666666666665), np.int64(22), np.int64(0))

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=0)} &= \frac{1}{3}\begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=0)} &= \begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=0)} &= \begin{bmatrix}2 \cdot 4 \cdot 8 & 0 \cdot 6 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [23]:
np.mean(A, axis=0), np.sum(A, axis=0), np.prod(A, axis=0)

(array([4.66666667, 2.66666667]), array([14,  8]), array([64,  0]))

In [24]:
A.mean(axis=0), A.sum(axis=0), A.prod(axis=0)

(array([4.66666667, 2.66666667]), array([14,  8]), array([64,  0]))

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=1)} &= \frac{1}{2}\begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=1)} &= \begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=1)} &= \begin{bmatrix}2 \cdot 0 & 4 \cdot 6 & 8 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [25]:
np.mean(A, axis=1), np.sum(A, axis=1), np.prod(A, axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [26]:
A.mean(axis=1), A.sum(axis=1), A.prod(axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [27]:
np.mean(A, axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [28]:
A.mean(axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [29]:
A - A.mean(axis=0, keepdims=True)

array([[-2.66666667, -2.66666667],
       [-0.66666667,  3.33333333],
       [ 3.33333333, -0.66666667]])

## Multiplicação de Matrizes

Para matrizes $\boldsymbol{X} \in \mathbb{R}^{a\times b}$ e $\boldsymbol{Y} \in \mathbb{R}^{b\times c}$, temos que
$\boldsymbol{XY} \in \mathbb{R}^{a\times c}$. No Numpy, essa operação é representada por $\texttt{X @ Y}$.

A multiplicação é definida por:
$$\begin{aligned}
(\boldsymbol{XY})_{ij} = \sum_k \boldsymbol{X}_{ik}\boldsymbol{Y}_{kj}
\end{aligned}$$

In [30]:
print(A @ B)
print("Dimensão de A @ B:", (A@B).shape)

[[ 2  6]
 [34 54]
 [18 38]]
Dimensão de A @ B: (3, 2)


Cuidado com as dimensões das matrizes:

In [31]:
try:
    B @ A
except Exception as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [32]:
print(A @ B @ v1)
print((A @ B) @ v1)

[ 28 332 204]
[ 28 332 204]


### Inversão de matrizes
Outra operação bastante comum é multiplicar uma matriz pela inversa dela...

Seja $\boldsymbol{B}$ uma matriz inversível, então $\boldsymbol{B}^{-1} \boldsymbol{B} = \boldsymbol{I}$


In [33]:
print(B)

[[1 3]
 [5 7]]


In [34]:
B_inv = np.linalg.inv(B)
print(B_inv)

[[-0.875  0.375]
 [ 0.625 -0.125]]


In [35]:
print(B_inv @ B)

[[1. 0.]
 [0. 1.]]


A inversa pode ser usada no produto com vetores:
$\boldsymbol{B}^{-1} \boldsymbol{v}_1$

In [36]:
print(B_inv @ v1)

[-3.25  2.75]


Porém, existe uma outra forma mais eficiente de computar a mesma coisa:

Se $\boldsymbol{B}^{-1} \boldsymbol{v}_1 = \boldsymbol{x}$, então $\boldsymbol{B} \boldsymbol{x} = \boldsymbol{v}_1$.
Ou seja, estamos resolvendo o sistema de equações lineares com coeficientes $\boldsymbol{B}$ e resultado $\boldsymbol{v}_1$

In [37]:
print(np.linalg.solve(B,v1))

[-3.25  2.75]


In [38]:
path

'./'

## Leitura de arquivos com dados

Normalmente os dados na disciplina serão recebidos no formato CSV. Isso significa que o dado é estruturado da seguinte maneira:
```
idade,pressão_sanguínea # Um cabeçalho opcional
39,144 # Dados separados por vírgulas ou outro separador
47,220
....
```

In [40]:
pressao_dataset = np.genfromtxt(path+'data/pressão.txt', delimiter=',', skip_header=1)
pressao_dataset

array([[ 39., 144.],
       [ 47., 220.],
       [ 45., 138.],
       [ 47., 145.],
       [ 65., 162.],
       [ 46., 142.],
       [ 67., 170.],
       [ 42., 124.],
       [ 67., 158.],
       [ 56., 154.],
       [ 64., 162.],
       [ 56., 150.],
       [ 59., 140.],
       [ 34., 110.],
       [ 42., 128.],
       [ 48., 130.],
       [ 45., 135.],
       [ 17., 114.],
       [ 20., 116.],
       [ 19., 124.],
       [ 36., 136.],
       [ 50., 142.],
       [ 39., 120.],
       [ 21., 120.],
       [ 44., 160.],
       [ 53., 158.],
       [ 63., 144.],
       [ 29., 130.],
       [ 25., 125.],
       [ 69., 175.]])

```
# idade, temperatura da água, comprimento
14,25,620
28,25,1315
....
```

In [ ]:
peixe_dataset = np.genfromtxt(path+'/peixe.txt', delimiter=',')
peixe_dataset

array([[  14.,   25.,  620.],
       [  28.,   25., 1315.],
       [  41.,   25., 2120.],
       [  55.,   25., 2600.],
       [  69.,   25., 3110.],
       [  83.,   25., 3535.],
       [  97.,   25., 3935.],
       [ 111.,   25., 4465.],
       [ 125.,   25., 4530.],
       [ 139.,   25., 4570.],
       [ 153.,   25., 4600.],
       [  14.,   27.,  625.],
       [  28.,   27., 1215.],
       [  41.,   27., 2110.],
       [  55.,   27., 2805.],
       [  69.,   27., 3255.],
       [  83.,   27., 4015.],
       [  97.,   27., 4315.],
       [ 111.,   27., 4495.],
       [ 125.,   27., 4535.],
       [ 139.,   27., 4600.],
       [ 153.,   27., 4600.],
       [  14.,   29.,  590.],
       [  28.,   29., 1305.],
       [  41.,   29., 2140.],
       [  55.,   29., 2890.],
       [  69.,   29., 3920.],
       [  83.,   29., 3920.],
       [  97.,   29., 4515.],
       [ 111.,   29., 4520.],
       [ 125.,   29., 4525.],
       [ 139.,   29., 4565.],
       [ 153.,   29., 4566.],
       [  

## Exercícios

### Computar a fórmula da normalização escore-Z

Dado um conjunto de dados $\boldsymbol{X} = [\boldsymbol{x}_1, \boldsymbol{x}_1, \ldots, \boldsymbol{x}_N]$, a normalização por escore-Z é dada por:
$$\tilde{\boldsymbol{x_i}} = \frac{\boldsymbol{x_i} - \boldsymbol{\mu}}{\boldsymbol{\sigma}}$$

Onde:
$$\begin{aligned}
\boldsymbol{\mu} &= \frac{1}{N}\sum_i^N \boldsymbol{x_i}\\
\boldsymbol{\sigma} &= \sqrt{\frac{1}{N-1}\sum_i^N (\boldsymbol{x_i}-\boldsymbol{\mu})^2}\\
\end{aligned}$$

A "desnormalização" pode ser feita por:
$$\boldsymbol{x_i} = \boldsymbol{\sigma}\tilde{\boldsymbol{x_i}} + \boldsymbol{\mu}$$

Use a fórmula para normalizar o conjunto de dados `peixe` sem usar nenhum `for` ou `while`.

In [ ]:
def mean(x):
  return x.sum(axis=0) / x.shape[0]

def std(x):
  mi = mean(x)
  n = x.shape[0]
  return (np.sum((x-mi)**2,axis=0)/(n))**0.5

In [ ]:
x = peixe_dataset
mi = mean(x)


In [ ]:
mean(peixe_dataset) == peixe_dataset.mean(axis=0)

array([ True,  True,  True])

In [ ]:
std(peixe_dataset) == peixe_dataset.std(axis=0)

array([ True,  True,  True])

In [ ]:
def normalize_zscore(x):
  mi = mean(x)
  std_ = std(x)
  params = (mi,std_)
  return (x-mi)/std_,params

def normalize_zscore_np(x):
    std_ = x.std(axis=0)
    mean_ = x.mean(axis=0)
    params = (x.mean(axis=0),x.std(axis=0))
    return (x-mean_)/std_,params

def denormalize_zscore(x,params):
    mi,std_ = params
    return x*std_+mi

In [ ]:
normalize_zscore(peixe_dataset)[0] == normalize_zscore_np(peixe_dataset)[0]

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ T

In [ ]:
fish_normalized, fish_params = normalize_zscore(peixe_dataset)

In [ ]:
denormalize_zscore(fish_normalized, fish_params) == peixe_dataset

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ T

### Encontrar raízes de funções

Dada uma função $f$, o seguinte procedimento (método de Newton-Raphson) consegue encontrar aproximar zeros desta função:

1. Inicialize $\tilde{x}_0$ com um chute inicial e escolha uma tolerância $\epsilon$;
2. Compute: $$\tilde{x}_{t} = \tilde{x}_{t-1} - \frac{f(\tilde{x}_{t-1})}{f'(\tilde{x}_{t-1})}$$
3. Repita o passo 2 até que $f(\tilde{x}_t) \leq \epsilon$.

Implemente esse procedimento para $f(x) = x^2 - 2$, teste seu resultado computando $\tilde{x} \cdot \tilde{x}$.

In [ ]:
f = lambda x: x**2 - 2
df = lambda x: 2*x

In [ ]:
from random import random
def newton_raphson(f,df,eps,x0=None):
    x0 = x0 or random()*100
    x = [x0]
    while True:
        i=len(x)
        x.append(x[-1] - f(x[-1])/df(x[-1]))
        print(f'{i}: x = {x[-1]:.6f} | f(x) = {f(x[-1]):.6f}')
        if abs(f(x[-1])) <= eps:
            print(f"Convergiu em {len(x)} iterações")
            return x[-1]


In [ ]:
xi = newton_raphson(f, df, 0.00000000001)

1: x = 14.627052 | f(x) = 211.950652
2: x = 7.381892 | f(x) = 52.492337
3: x = 3.826413 | f(x) = 12.641435
4: x = 2.174548 | f(x) = 2.728658
5: x = 1.547140 | f(x) = 0.393641
6: x = 1.419924 | f(x) = 0.016184
7: x = 1.414225 | f(x) = 0.000032
8: x = 1.414214 | f(x) = 0.000000
9: x = 1.414214 | f(x) = 0.000000
Convergiu em 10 iterações


In [ ]:
round(f(xi),4)

0.0

# Regressão linear via mínimos quadrados ordinários (OLS)

Como visto na aula de regressão linear, dado o seguinte problema:
$$\begin{aligned}
\hat{\boldsymbol{y}} = \boldsymbol{X}\boldsymbol{w}\\
\text{Queremos encontrar:}\\
\hat{\boldsymbol{w}} = \arg\min_{\boldsymbol{w}} ||\boldsymbol{y} - \boldsymbol{X}\boldsymbol{w}||^2
\end{aligned}$$

Como visto, sabemos que:
$$\hat{\boldsymbol{w}} = (\boldsymbol{X}^{\top}\boldsymbol{X})^{-1} \boldsymbol{X}^{\top}\boldsymbol{y}$$

Obtenha um modelo linear para predizer o comprimento de um peixe a partir de sua idade e da temperatura da água. Para isso, encontre o $\hat{\boldsymbol{w}}$ pro dataset `peixe` onde:
$$\boldsymbol{X} = [\mathbf{1}^{\top} \;,\; \mathtt{peixe\underline{}dataset[:,[0,1]}]\\
\boldsymbol{y} = \mathtt{peixe\underline{}dataset[:,[2]]}$$

Sem utilizar estrutura de repetição alguma, calcule a raíz do erro quadrático médio:
$$\mathrm{RMSE} = \sqrt{\frac{1}{n}\sum_i^n (\boldsymbol{y} - \hat{\boldsymbol{y}})^2}$$

In [ ]:
def rmse(y, y_pred):
    return mean((y - y_pred)**2)**0.5

In [ ]:
x_feat_norm, x_params = normalize_zscore(peixe_dataset[:,[0,1]])

In [ ]:
X = np.c_[np.ones(peixe_dataset.shape[0]), x_feat_norm]

In [ ]:
X

array([[ 1.        , -1.5718109 , -1.34164079],
       [ 1.        , -1.2537309 , -1.34164079],
       [ 1.        , -0.9583709 , -1.34164079],
       [ 1.        , -0.6402909 , -1.34164079],
       [ 1.        , -0.32221091, -1.34164079],
       [ 1.        , -0.00413091, -1.34164079],
       [ 1.        ,  0.31394909, -1.34164079],
       [ 1.        ,  0.63202909, -1.34164079],
       [ 1.        ,  0.95010908, -1.34164079],
       [ 1.        ,  1.26818908, -1.34164079],
       [ 1.        ,  1.58626908, -1.34164079],
       [ 1.        , -1.5718109 , -0.4472136 ],
       [ 1.        , -1.2537309 , -0.4472136 ],
       [ 1.        , -0.9583709 , -0.4472136 ],
       [ 1.        , -0.6402909 , -0.4472136 ],
       [ 1.        , -0.32221091, -0.4472136 ],
       [ 1.        , -0.00413091, -0.4472136 ],
       [ 1.        ,  0.31394909, -0.4472136 ],
       [ 1.        ,  0.63202909, -0.4472136 ],
       [ 1.        ,  0.95010908, -0.4472136 ],
       [ 1.        ,  1.26818908, -0.447

In [ ]:
y, y_params = normalize_zscore(peixe_dataset[:,[2]])
y

array([[-1.893348  ],
       [-1.36433777],
       [-0.75159932],
       [-0.38623974],
       [ 0.00195481],
       [ 0.32545027],
       [ 0.62991659],
       [ 1.03333445],
       [ 1.08281023],
       [ 1.11325686],
       [ 1.13609183],
       [-1.88954217],
       [-1.44045435],
       [-0.75921097],
       [-0.23020075],
       [ 0.11232385],
       [ 0.69080985],
       [ 0.91915958],
       [ 1.05616943],
       [ 1.08661606],
       [ 1.13609183],
       [ 1.13609183],
       [-1.91618297],
       [-1.37194943],
       [-0.736376  ],
       [-0.16550166],
       [ 0.6184991 ],
       [ 0.6184991 ],
       [ 1.07139274],
       [ 1.07519857],
       [ 1.0790044 ],
       [ 1.10945103],
       [ 1.1102122 ],
       [-1.91618297],
       [-1.44806601],
       [-0.9076383 ],
       [-0.736376  ],
       [-0.3025115 ],
       [-0.06655011],
       [-0.05893845],
       [-0.05132679],
       [ 0.05523642],
       [ 0.11384618],
       [ 0.08111605]])

In [ ]:
w = np.linalg.inv(X.T @ X) @ X.T @ y
w

array([[ 2.91433544e-16],
       [ 8.79115728e-01],
       [-1.81117971e-01]])

In [ ]:
w2, _, _, _ = np.linalg.lstsq(X, y, rcond=None)
w2

array([[ 6.69489674e-17],
       [ 8.79115728e-01],
       [-1.81117971e-01]])

In [ ]:
w == w2

array([[False],
       [False],
       [False]])

In [ ]:
X @ w

array([[-1.13880842],
       [-0.85917929],
       [-0.59952367],
       [-0.31989455],
       [-0.04026542],
       [ 0.23936371],
       [ 0.51899284],
       [ 0.79862197],
       [ 1.0782511 ],
       [ 1.35788022],
       [ 1.63750935],
       [-1.30080526],
       [-1.02117613],
       [-0.76152051],
       [-0.48189138],
       [-0.20226226],
       [ 0.07736687],
       [ 0.356996  ],
       [ 0.63662513],
       [ 0.91625426],
       [ 1.19588339],
       [ 1.47551251],
       [-1.4628021 ],
       [-1.18317297],
       [-0.92351735],
       [-0.64388822],
       [-0.36425909],
       [-0.08462997],
       [ 0.19499916],
       [ 0.47462829],
       [ 0.75425742],
       [ 1.03388655],
       [ 1.31351568],
       [-1.62479894],
       [-1.34516981],
       [-1.08551419],
       [-0.80588506],
       [-0.52625593],
       [-0.2466268 ],
       [ 0.03300232],
       [ 0.31263145],
       [ 0.59226058],
       [ 0.87188971],
       [ 1.15151884]])

In [ ]:
def ols(X,y):
  w = np.linalg.inv(X.T @ X) @ X.T @ y
  return X @ w, w

In [ ]:
y_pred_norm = ols(X,y)[0]
y_pred = denormalize_zscore(y_pred_norm, y_params)

In [ ]:
rmse(y, y_pred)

array([3323.33681729])

# Regressão linear via gradiente descendente (GD)

Sendo $\alpha$ um passo de aprendizagem, $N$ o número de observações disponíveis e $t$ a iteração atual do algoritmo, os parâmetros $\boldsymbol{w}$ podem ser atualizados via algoritmo GD:

$$\boldsymbol{w}(t) = \boldsymbol{w}(t-1) + \alpha \frac{1}{N}\sum_{i=1}^{N} e_i(t-1) \boldsymbol{x}_i,$$
$$\text{em que } e_i(t-1) = y_i - \boldsymbol{w}^{\top}(t-1)\boldsymbol{x}_i$$

Normalize os dados retirando a média e dividindo pelo desvio padrão (entrada e saída). Na predição, desfaça a normalização para computar o RMSE.

In [ ]:
a = 0.000001
N = X.shape[0]
t = 0
w = []
e = []

In [ ]:
N = X.shape[0]
t = 0
a = random()
w = []
e = []
e.append(y[i]-w[t-1].T@X[i] for i in range(N))
w.append(w[-1]+a*(e[-2])/N)

IndexError: list index out of range

In [ ]:
import numpy as np

def gradient_descent_linear_regression(X, y, alpha=0.01, max_iter=10000, tol=1e-8):
    X_norm_features, X_params = normalize_zscore(X)
    y_norm, y_params = normalize_zscore(y)

    X_norm = np.c_[np.ones((X_norm_features.shape[0], 1)), X_norm_features]

    N, p = X_norm.shape
    w = np.zeros((p, 1))

    for _ in range(max_iter):
        e = y_norm - X_norm @ w
        w_new = w + alpha * (X_norm.T @ e) / N

        if np.linalg.norm(w_new - w) < tol:
            w = w_new
            break

        w = w_new

    y_pred_norm = X_norm @ w
    y_pred = denormalize_zscore(y_pred_norm, y_params)
    error = rmse(y, y_pred)

    return w, y_pred, error

In [ ]:
import numpy as np

def gradient_descent_linear_regression(X, y, alpha=0.01, max_iter=10000, tol=1e-8):
    X_norm_features, X_params = normalize_zscore(X)
    y_norm, y_params = normalize_zscore(y)

    X_norm = np.c_[np.ones((X_norm_features.shape[0], 1)), X_norm_features]

    N, p = X_norm.shape
    w = np.zeros((p, 1))

    errors = []

    for _ in range(max_iter):
        y_pred_norm = X_norm @ w
        e = y_norm - y_pred_norm

        y_pred = denormalize_zscore(y_pred_norm, y_params)
        errors.append(rmse(y, y_pred))

        w_new = w + alpha * (X_norm.T @ e) / N

        if np.linalg.norm(w_new - w) < tol:
            w = w_new
            break

        w = w_new

    y_pred_norm = X_norm @ w
    y_pred = denormalize_zscore(y_pred_norm, y_params)

    return w, y_pred, errors

import matplotlib.pyplot as plt

X = peixe_dataset[:, [0, 1]]
y = peixe_dataset[:, [2]]

w_gd, y_pred_gd, errors = gradient_descent_linear_regression(X, y, alpha=0.05)

plt.plot(errors)
plt.xlabel("Iterações")
plt.ylabel("RMSE")
plt.title("Convergência do Gradiente Descendente")
plt.grid()
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

X = peixe_dataset[:, [0, 1]]
y = peixe_dataset[:, [2]]

w_gd, y_pred_gd, errors = gradient_descent_linear_regression(X, y, alpha=0.05)

temp_mean = X[:,1].mean()

x_vals = np.linspace(X[:,0].min(), X[:,0].max(), 100)
X_line = np.c_[x_vals, np.full_like(x_vals, temp_mean)]

X_norm_features, X_params = normalize_zscore(X)
y_norm, y_params = normalize_zscore(y)

X_line_norm = (X_line - X_params[0]) / X_params[1]
X_line_norm = np.c_[np.ones((X_line_norm.shape[0],1)), X_line_norm]

y_line_norm = X_line_norm @ w_gd
y_line = denormalize_zscore(y_line_norm, y_params)

plt.scatter(X[:,0], y, label="Dados reais")
plt.plot(x_vals, y_line, color='red', label="Reta (temp média)")

plt.xlabel("Idade")
plt.ylabel("Comprimento")
plt.title("Regressão linear (fixando temperatura)")
plt.legend()
plt.grid()
plt.show()

In [ ]:
gradient_descent_linear_regression(peixe_dataset[:,[0,1]], y, max_iter=1000000)

In [ ]:
np.zeros((5,1))

In [ ]:
peixe_dataset @ np.zeros((3,1))

# Regressão linear via gradiente descendente estocástico (SGD)

Sendo $\alpha$ um passo de aprendizagem, $N$ o número de observações disponíveis e $t$ a iteração atual do algoritmo, os parâmetros $\boldsymbol{w}$ podem ser atualizados via algoritmo SGD:

$$\boldsymbol{w}(t) = \boldsymbol{w}(t-1) + \alpha e_i(t-1) \boldsymbol{x}_i,$$
$$\text{em que } e_i(t-1) = y_i - \boldsymbol{w}^{\top}(t-1)\boldsymbol{x}_i$$

Normalize os dados retirando a média e dividindo pelo desvio padrão (entrada e saída). Na predição, desfaça a normalização para computar o RMSE.

In [ ]:
# Escreva o código aqui